import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const ui = {
  gu: {
    home: 'હોમ',
    history: 'ઇતિહાસ',
    seva: 'સેવા',
    gallery: 'ગેલેરી',
    videos: 'વિડીયો',
    donate: 'દાન',
    contact: 'સંપર્ક',
    changeLanguage: 'English',
    donateNow: 'દાન કરો',
    viewGallery: 'ગેલેરી જુઓ',
    exploreSeva: 'સેવા જુઓ',
    dailyMeals: 'દૈનિક પ્રસાદ',
    festivalDevotees: 'ઉત્સવના ભક્તો',
    annshetra: 'અન્નક્ષેત્ર',
    founded: 'શ્રદ્ધા અને સેવાનું પવિત્ર ધામ',
    aboutTemple: 'મંદિર વિશે',
    dailyWorship: 'દૈનિક આરતી',
    dailyWorshipText: 'સવાર અને સાંજની આરતી',
    sacredTradition: 'પવિત્ર પરંપરા',
    sacredTraditionText: 'સદીઓનો આધ્યાત્મિક વારસો',
    ourSeva: 'અમારી સેવા',
    serviceDevotion: 'સેવા એ ભક્તિ',
    serviceSubtitle: 'મંદિરની સેવા પ્રવૃત્તિઓ સમાજસેવાના મુખ્ય સ્તંભો છે.',
    learnMore: 'વધુ જાણો',
    sacredCalendar: 'પવિત્ર પર્વો',
    festivalsCelebrations: 'મંદિરમાં ઉજવાતા પાવન અવસરો અને ઉત્સવો',
    festivalsSubtitle: 'મંદિરમાં ભક્તિભાવ અને ભવ્યતાથી ઉજવાતા મુખ્ય પર્વો.',
    upcoming: 'આવનાર',
    viewAllFestivals: 'બધા ઉત્સવો જુઓ',
    visualStories: 'પવિત્ર ક્ષણો',
    photoGallery: 'ફોટો ગેલેરી',
    gallerySubtitle: 'મંદિરના ઉત્સવો, દર્શન અને સેવાકાર્યોના ફોટા.',
    fullGallery: 'પૂર્ણ ગેલેરી જુઓ',
    supportMission: 'સેવામાં સહયોગ',
    contributeNow: 'દાન કરો',
    getInTouch: 'સંપર્કમાં રહો',
    visitConnect: 'મુલાકાત અથવા સંપર્ક',
    contactSubtitle: 'દર્શન, નિવાસ અથવા માર્ગદર્શન માટે ભક્તો અને મુલાકાતીઓ સંપર્ક કરી શકે છે.',
    address: 'સરનામું',
    phone: 'ફોન',
    email: 'ઈમેઈલ',
    website: 'વેબસાઈટ',
    comingSoon: 'ટૂંક સમયમાં',
    quickLinks: 'ઝડપી લિંક્સ',
    footerSeva: 'અમારી સેવા',
    footerDesc: 'ગુજરાતમાં ભક્તિ, સમાજસેવા અને પવિત્ર પરંપરાનું જીવંત કેન્દ્ર.',
    footerTagline: 'સેવા · ભક્તિ · જ્ઞાન',
    built: 'ભક્તિથી બનાવેલ.',
    historySubtitle: 'વડવાળા ધામનો ગૌરવશાળી ઇતિહાસ',
    noHistory: 'ઇતિહાસની માહિતી ટૂંક સમયમાં ઉપલબ્ધ થશે',
    parampara: 'આચાર્યશ્રી પરંપરા',
    paramparaSubtitle: 'ગાદીસ્થ આચાર્યશ્રીઓની પરંપરા',
    all: 'બધા',
    noPhotos: 'આ કેટેગરીમાં હાલમાં કોઈ ફોટો નથી',
    donationTitle: 'દાન – સેવા',
    donationSubtitle: 'મંદિરના વિવિધ સેવા કાર્યોમાં આપનો સહકાર',
    donationPurposes: 'દાનના હેતુઓ',
    donationPurposesSub: 'નીચેના સેવા કાર્યોમાં દાન આપી શકો છો',
    howToDonate: 'દાન કેવી રીતે કરવું',
    noDonation: 'દાનની માહિતી ટૂંક સમયમાં ઉપલબ્ધ થશે',
    noPayment: 'ચુકવણીની માહિતી ટૂંક સમયમાં ઉપલબ્ધ થશે',
    importantNote: 'મહત્વની નોંધ',
    activitiesTitle: 'સેવા અને ઉત્સવો',
    activitiesSubtitle: 'મંદિરની સેવા, શૈક્ષણિક અને ધાર્મિક પ્રવૃત્તિઓ',
    ourMission: 'અમારો ધ્યેય',
    serviceActivities: 'સેવા પ્રવૃત્તિઓ',
    activitiesSoon: 'પ્રવૃત્તિઓ ટૂંક સમયમાં ઉપલબ્ધ થશે',
    festivals: 'ઉત્સવો',
    festivalInfoSoon: 'ઉત્સવની માહિતી ટૂંક સમયમાં ઉપલબ્ધ થશે',
    videosTitle: 'વિડીયો અને રીલ્સ',
    videosSubtitle: 'મંદિરના ઉત્સવો અને દર્શનના વિડીયો',
    latestVideos: 'નવા વિડીયો',
    latestReels: 'નવી રીલ્સ',
    noVideos: 'હાલમાં કોઈ વિડીયો ઉપલબ્ધ નથી',
    noReels: 'હાલમાં કોઈ રીલ્સ ઉપલબ્ધ નથી',
    contactUs: 'અમારો સંપર્ક કરો',
    reachOut: 'સંપર્ક કરો',
    contactInfo: 'સંપર્ક માહિતી',
    sendMessage: 'સંદેશ મોકલો',
    writeToUs: 'અમને લખો',
    name: 'તમારું નામ *',
    phoneNumber: 'ફોન નંબર',
    message: 'તમારો સંદેશ *',
    namePlaceholder: 'તમારું નામ લખો',
    phonePlaceholder: 'ફોન નંબર લખો',
    emailPlaceholder: 'ઈમેઈલ લખો',
    messagePlaceholder: 'તમારો સંદેશ લખો...',
    sending: 'મોકલી રહ્યા છીએ...',
    sent: 'તમારો સંદેશ સફળતાપૂર્વક મોકલાયો!',
    send: 'સંદેશ મોકલો',
    findUs: 'અમને શોધો',
    dhaja: 'ધજા',
    gaushala: 'ગૌશાળા',
    location: 'અમારું સ્થાન',
    // ── Gurus ──
    guruEyebrow: 'ધર્મગુરુ પરંપરા',
    guruParampara: 'ગુરુ પરંપરા',
    readMore: 'વધુ વાંચો',
    loadingGurus: 'લોડ થઈ રહ્યું છે...',
    guruNotFound: 'ગુરુ વિશે માહિતી ઉપલબ્ધ નથી',
    backToHome: 'હોમ પેજ પર પાછા ફરો',
    back: 'પાછા',
    born: 'જન્મ',
    birthplace: 'જન્મસ્થળ',
    lifeHistory: 'જીવન ચરિત્ર',
    biographyTitle: 'પૂર્ણ જીવન ગાથા',
    teachings: 'ઉપદેશ અને સંદેશ',
    teachingsTitle: 'મુખ્ય સિદ્ધાંતો અને સંદેશો',
    timeline: 'સમયરેખા',
    timelineTitle: 'મહત્વના સેવા કાર્યો અને ઘટનાક્રમ',
    galleryTitle: 'દર્શન અને સેવા છબીઓ',
    upcomingTithis: 'આવનાર તિથિઓ',
    tithisSubtitle: 'ક્યારેય મૂંઝવણમાં ન પડો - આગામી પૂનમ, બીજ અને અન્ય મહત્વપૂર્ણ દિવસોની માહિતી અહીં જુઓ.',
    nextPunamIs: 'આગામી પૂનમ:',
    nextBijIs: 'આગામી બીજ:',
    filterAll: 'બધી તિથિઓ',
    filterPunam: 'ફક્ત પૂનમ',
    filterBij: 'ફક્ત બીજ',
    nextBadge: 'આગામી',
  },
  en: {
    home: 'Home',
    history: 'History',
    seva: 'Seva',
    gallery: 'Gallery',
    videos: 'Videos',
    donate: 'Donate',
    contact: 'Contact',
    changeLanguage: 'ગુજરાતી',
    donateNow: 'Donate',
    viewGallery: 'View Gallery',
    exploreSeva: 'Explore Seva',
    dailyMeals: 'Daily Meals',
    festivalDevotees: 'Festival Devotees',
    annshetra: 'Annshetra',
    founded: 'Founded on Faith · Serving Humanity',
    aboutTemple: 'About the Temple',
    dailyWorship: 'Daily Worship',
    dailyWorshipText: 'Morning and evening aarti',
    sacredTradition: 'Sacred Tradition',
    sacredTraditionText: 'Centuries of spiritual heritage',
    ourSeva: 'Our Seva',
    serviceDevotion: 'Service as Devotion',
    serviceSubtitle: "The temple's mission flows through community service, education, worship, and care.",
    learnMore: 'Learn more',
    sacredCalendar: 'Sacred Calendar',
    festivalsCelebrations: 'Festivals & Celebrations',
    festivalsSubtitle: 'Major religious festivals celebrated at the temple with devotion and grandeur.',
    upcoming: 'Upcoming',
    viewAllFestivals: 'View All Festivals',
    visualStories: 'Visual Stories',
    photoGallery: 'Photo Gallery',
    gallerySubtitle: 'Glimpses of temple festivals, darshan, and service activities.',
    fullGallery: 'View Full Gallery',
    supportMission: 'Support the Mission',
    contributeNow: 'Contribute Now',
    getInTouch: 'Get in Touch',
    visitConnect: 'Visit or Connect',
    contactSubtitle: 'Devotees and visitors can reach out for darshan, accommodation, or guidance.',
    address: 'Address',
    phone: 'Phone',
    email: 'Email',
    website: 'Website',
    comingSoon: 'Coming soon',
    quickLinks: 'Quick Links',
    footerSeva: 'Our Seva',
    footerDesc: 'A living center of devotion, community service, and sacred tradition in Gujarat.',
    footerTagline: 'Seva · Bhakti · Gyaan',
    attribution: 'Content reference',
    originalUi: 'All UI design is original and not affiliated with the source website.',
    built: 'Built with devotion.',
    historySubtitle: 'The proud history of Vadwala Dham',
    noHistory: 'History information will be available soon',
    parampara: 'Acharya Parampara',
    paramparaSubtitle: 'Lineage of the presiding Acharyas',
    all: 'All',
    noPhotos: 'No photos are available in this category',
    donationTitle: 'Donation & Seva',
    donationSubtitle: 'Support the temple service activities',
    donationPurposes: 'Donation Purposes',
    donationPurposesSub: 'You can donate toward the service activities below',
    howToDonate: 'How to Donate',
    noDonation: 'Donation information will be available soon',
    noPayment: 'Payment information will be available soon',
    importantNote: 'Important Note',
    activitiesTitle: 'Seva & Festivals',
    activitiesSubtitle: 'Temple service, education, and religious activities',
    ourMission: 'Our Mission',
    serviceActivities: 'Service Activities',
    activitiesSoon: 'Activities coming soon',
    festivals: 'Festivals',
    dhaja: 'Dhaja',
    gaushala: 'Gaushala',
    festivalInfoSoon: 'Festival information coming soon',
    videosTitle: 'Videos and Reels',
    videosSubtitle: 'Temple festival and darshan videos',
    latestVideos: 'Latest Videos',
    latestReels: 'Latest Reels',
    noVideos: 'No videos are available right now',
    noReels: 'No reels are available right now',
    contactUs: 'Contact Us',
    reachOut: 'Reach Out',
    contactInfo: 'Contact Information',
    sendMessage: 'Send a Message',
    writeToUs: 'Write to Us',
    name: 'Your Name *',
    phoneNumber: 'Phone Number',
    message: 'Your Message *',
    namePlaceholder: 'Enter your name',
    phonePlaceholder: 'Enter phone number',
    emailPlaceholder: 'Enter email',
    messagePlaceholder: 'Write your message...',
    sending: 'Sending...',
    sent: 'Your message was sent successfully!',
    send: 'Send Message',
    findUs: 'Find Us',
    location: 'Our Location',
    // ── Gurus ──
    guruEyebrow: 'Holy Gurus',
    guruParampara: 'Guru Parampara',
    readMore: 'Read More',
    loadingGurus: 'Loading guru details...',
    guruNotFound: 'Guru details not found',
    backToHome: 'Back to Home',
    back: 'Back',
    born: 'Born',
    birthplace: 'Birthplace',
    lifeHistory: 'Biography',
    biographyTitle: 'Life History & Contributions',
    teachings: 'Teachings & Message',
    teachingsTitle: 'Key Themes and Teachings',
    timeline: 'Timeline',
    timelineTitle: 'Key Milestones and Service Timeline',
    galleryTitle: 'Darshan & Service Gallery',
    upcomingTithis: 'Upcoming Tithis',
    tithisSubtitle: 'Never get confused again – see the next Punam, Bij and other important days here.',
    nextPunamIs: 'Next Punam:',
    nextBijIs: 'Next Bij:',
    filterAll: 'All Tithis',
    filterPunam: 'Punam Only',
    filterBij: 'Bij Only',
    nextBadge: 'Next',
  },
};

const exactEnglish = {
  // -- Acharyas Names --
  'શ્રી નીલકંઠ સ્વામી': 'Shree Nilkanth Swami',
  'શ્રી રઘુનાથ સ્વામી': 'Shree Raghunath Swami',
  'શ્રી યાદવ સ્વામી': 'Shree Yadav Swami',
  'શ્રી ષટપ્રજ્ઞદાસજી': 'Shree Shatpragnyadasji',
  'શ્રી લબ્ધરામજી': 'Shree Labhdharamji',
  'શ્રી રત્નદાસજી': 'Shree Ratnadasji',
  'શ્રી માનદાસજી': 'Shree Manadasji',
  'શ્રી કૃષ્ણદાસજી': 'Shree Krishnadasji',
  'શ્રી ઓધવદાસજી': 'Shree Odhavdasji',
  'શ્રી ગોકુલદાસજી': 'Shree Gokuldasji',
  'શ્રી ભાવદાસજી': 'Shree Bhavdasji',
  'શ્રી ગુલાબદાસજી': 'Shree Gulabdasji',
  'શ્રી કેવળદાસજી': 'Shree Kevaldasji',
  'શ્રી મેઘદાસજી': 'Shree Meghdasji',
  'શ્રી યમુનાદાસજી': 'Shree Yamunadasji',
  'શ્રી ગંગારામજી': 'Shree Gangaramji',
  'શ્રી ગોવિંદરામજી': 'Shree Govindramji',
  'શ્રી રઘુવરદાસજી': 'Shree Raghuverdasji',
  'શ્રી જીવરામદાસજી': 'Shree Jeevramdasji',
  'શ્રી ગોમતીદાસજી': 'Shree Gomtidasji',
  'શ્રી કલ્યાણદાસજી': 'Shree Kalyandasji',
  'શ્રી કનીરામદાસજી': 'Shree Kaniramdasji',

  // -- Acharyas Biographies --
  'જગદ્ગુરુ શ્રી રામાનુજાચાર્યજીની પરંપરાના મહાન સંત. દૂધરેજ ધામની ઉજળી પરંપરાના પ્રથમ યતિ, જેમણે પવિત્ર ગંગાજીમાં જળસમાધિ લીધી હતી.': 'A great saint of the Ramanujacharya lineage. The first ascetic of the Dudhrej Dham lineage who took water samadhi in the holy Ganges.',
  'નીલકંઠદાસજીના અનન્ય શિષ્ય, જેમનો જન્મ ધરાસુચટ્ટી ગામમાં થયો હતો. ઝીંઝુવાડાના રણમાં ધુણો ધખાવી સનાતન ધર્મનો પ્રચાર કર્યો અને જળસમાધિ લીધી.': 'The dedicated disciple of Nilkanthdasji, born in Dharasuchatti. He established a sacred fire in the desert of Jhinjhuwada to propagate Sanatan Dharma and took water samadhi.',
  'અખંડ ભજન, ધુણી અને તપસ્યાના પ્રતીક સંત. ઝીંઝુવાડા રણને સ્વર્ગ સમાન બનાવી જીલેશ્વર સરોવરના કિનારે અખંડ ભજન આરાધના કરી.': 'A symbol of continuous devotion and penance, who turned the desert of Jhinjhuwada into a heavenly abode through prayer by the Jileshwar lake.',
  'ઝીંઝુવાડાના સામંતસિંહ અને અમરસિંહ રાજકુમારોને વૈરાગ્ય આપી દીક્ષિત કર્યા. અયોધ્યાથી લાવેલા વડના દાતણ રોપીને દૂધરેજ ધામમાં પવિત્ર વટવૃક્ષ (વડલા) ની સ્થાપના કરી.': 'Initiated the princes of Jhinjhuwada into asceticism. He planted the sacred Banyan tree at Dudhrej Dham using a banyan twig from Ayodhya.',
  'પાટણ જિલ્લાના દાસદ ગામના રબારી સમાજના તેજસ્વી સંત. ષટપ્રજ્ઞદાસજીના આશીર્વાદથી ગાદીપતિ બન્યા અને ૧૪ પરગણાના રબારી સમાજમાં ધર્મ અને સંસ્કારનું સિંચન કરી જળ સમાધિ લીધી.': 'A brilliant saint of the Rabari community from Dasad. He spread spirituality across 14 regions and took water samadhi.',
  'પાટણવાડાના ગોવના ગામના રબારી સમાજના સિદ્ધ સંત, જેમણે અદ્ભુત યોગસિદ્ધિ દ્વારા ગંગાજી અને રણમાં ડૂબતા લોકોને બચાવવાના પરચાઓ આપ્યા હતા.': 'A realized yogi of the Rabari community from Gova, who performed miracles to save people from drowning in the Ganges and desert.',
  'અતિ ભજનાનંદી, ત્યાગી અને પરમ વૈરાગ્યવાન સંત. ઉત્તર ગુજરાતના મેરણા ગામના રબારી સમાજના ભાગ્યશાળી પરિવારમાં જન્મ્યા અને ધામનો ભક્તિભાવ વધાર્યો.': 'A highly devotional and detached saint from Merna. He dedicated his life to spiritual upliftment and temple service.',
  'ઉત્તર ગુજરાતના કરજીસણ (કલોલ) ગામના રબારી સમાજના યોગદ્રષ્ટા સંત. સમગ્ર જીવન સેવામાં સમર્પિત કરી વડવાળા ધામની કીર્તિ દેશભરમાં પ્રસરાવી.': 'A visionary saint of the Rabari community from Karjisan. He dedicated his life to service and spread the temple\'s glory nationwide.',
  'કૃષ્ણદાસજીના શિષ્ય અને સગુણ ઉપાસનાના આરાધક સંત. ઉત્તર ગુજરાતના ખાવડ ગામના રબારી સમાજ પરિવારમાં જન્મ. ભક્તિ અને સેવાની ઉજળી પરંપરા જાળવી.': 'A devotee of worship and disciple of Krishnadasji, born in Khabhad. He preserved the lineage of faith and service.',
  'ટૂંકા ગાળામાં અનેક ભગવત કાર્યો કરી આધ્યાત્મિક જ્યોત પ્રજ્વલિત રાખનારા દ્રષ્ટિવંત અને પરમ પવિત્ર સંત.': 'A visionary and pure saint who kept the spiritual flame alive by performing numerous divine tasks in a short tenure.',
  'અતિ લાગણીશીલ, વિવેક સંપન્ન અને સગુણ રામચંદ્રજીના પરમ ઉપાસક સંત, જેમણે અખંડ ચેતના જાગૃત રાખી.': 'A deeply compassionate and wise saint who was a dedicated devotee of Lord Rama and maintained spiritual awakening.',
  'કાર્યકુશળ અને સંગીત કલાના અજોડ જાણકાર સંત, જેમણે સંતવાણી અને ભગવત કાર્ય દ્વારા સેવાની જ્યોત જલતી રાખી.': 'An efficient administrator and expert in music, who kept the flame of service burning through devotional singing.',
  'અતિ ભજનાનંદી, ત્યાગી, અને અન્નદાનનો મહિમા વધારનાર સિદ્ધ સંત, જેમણે કોઈ પણ સંપત્તિમાં મોહ રાખ્યા વિના સેવા કરી.': 'A detached and realized saint who emphasized the importance of food donation (Annshetra) and served without worldly attachments.',
  'ગૌ અને બ્રાહ્મણ પ્રતિપાળ સંત. ઝાલાવાડના ભદ્રેશી ગામના રબારી પરિવારમાં જન્મ. દુષ્કાળ સમયે ગૌસેવા અર્થે પોતાના હાથથી પથ્થર ખસેડી પાણીનું ઝરણું પ્રગટ કર્યું, જેને મેઘ તલાવડી કહે છે.': 'Protector of cows and saints, born in Bhadreshi. During a drought, he uncovered a freshwater spring for cows, known as Megh Talavadi.',
  'વાણી અને વર્તનમાં પવિત્રતા, ગરીબોની સેવા અને ધર્મના સંસ્કારોનો સદાય પ્રસાર કરનાર પરમ આદરણીય સંત.': 'A highly revered saint who always spread purity, service to the poor, and moral values through his life.',
  'સાદાઈ, સાત્વિકતા અને સહનશીલતાના મૂર્તિમંત સંત. ધ્રાંગધ્રાના રાજવી માનસિંહજીને વૈરાગ્યનો મહિમા સમજાવી વડવાળા મંદિરના ભવ્ય શિખરબદ્ધ બાંધકામની કડી જોડી.': 'A saint of simplicity and patience. He inspired the king of Dhrangadhra to construct the grand temple spire at Dudhrej.',
  'ટૂંકા શાસનકાળમાં પણ ધામની આધ્યાત્મિક ગરિમા, સામાજિક સેવા અને ગૌસેવાના કાર્યોને કૂશળતાપૂર્વક ચલાવનારા સંત.': 'A saint who efficiently managed the spiritual dignity, social services, and cow protection activities of the temple during his short tenure.',
  'ઝાલાવાડના ગોમટા ગામના વતની તેજસ્વી અને સાત્વિક સંત. દેશભરમાં વડવાળા ધામની સેવાની કીર્તિ સ્થાપિત કરી અને ચાર ધામ યાત્રા તથા સાધુ સંમેલનો કર્યા.': 'A bright and pure saint from Gomta. He established the glory of temple services nationwide and organized grand saint assemblies.',
  'ઝાલાવાડના રવળીયાવદર ગામના રબારી જ્ઞાતિના પવિત્ર સંત. ગુરુ રઘુવરદાસજીના સાનિધ્યમાં વૈરાગ્ય ધારણ કરી ધામની આધ્યાત્મિક પ્રતિષ્ઠા અને અન્નક્ષેત્ર સેવા વધારી.': 'A holy saint of the Rabari community from Ravliyavadar. Under Guru Raghuverdasji, he expanded the food hall (Annshetra) services.',
  'બગસરાના કાગદડી ગામના રબારી સમાજના ક્રાંતિકારી સંત. કાશીમાં ૧૮ વર્ષ વેદાંત અભ્યાસ કરી વેદાંતતીર્થ બન્યા. અંધશ્રદ્ધા અને કુરિવાજોના વિરોધી અને શિક્ષણના હિમાયતી હતા.': 'A revolutionary saint from Kagdadi. He studied Vedanta for 18 years in Kashi, opposing superstition and advocating education.',
  'ગોતા (અમદાવાદ) ના રબારી સમાજમાં જન્મેલા પરમ વિવેક સંપન્ન સંત, જેમણે સામાજિક અને શૈક્ષણિક ક્ષેત્રે ભગીરથ સુધારા કરી વડવાળા ધામની ગાદી શોભાવી.': 'Born in Gota, he initiated social and educational reforms, elevating the management of the temple seat.',
  'સાંકરવડા (અમરેલી) માં જન્મેલા ૧૦૦૮ મહામંડલેશ્વર. ગુરુ કલ્યાણદાસજીના શરણમાં દીક્ષા મેળવી ધામની ધાર્મિક, શૈક્ષણિક અને અન્નક્ષેત્ર પ્રવૃત્તિઓને દેશભરમાં સુપ્રસિદ્ધ કરી.': 'The current 1008 Mahamandaleshwar, born in Sakravada. He has made the temple\'s religious, educational, and service activities famous worldwide.',

  'શ્રી વડવાળા મંદિર દુધરેજધામ': 'Shree Vadwala Mandir Dudhrejdham',
  'શ્રી વડવાળાદેવના પવિત્ર ધામમાં આપનું સ્વાગત છે': 'Welcome to the sacred abode of Shri Vadwaladev.',
  'અન્નક્ષેત્ર : અભિયાગત સેવા': 'Annshetra: Devotee Meal Service',
  'દરરોજ ૨૪ કલાક અન્નક્ષેત્ર': '24-hour daily meal service',
  'ગૌશાળા : ઉત્તમ ઓલાદનું રક્ષણ': 'Gaushala: Care for Indigenous Cattle',
  'ઉત્તમ ગાયોનો ઉછેર અને સેવા': 'Care and service for indigenous cattle',
  'શૈક્ષણિક કાર્ય': 'Educational Service',
  'કુમાર છાત્રાલય, કન્યા છાત્રાલય, હાઈસ્કુલ': 'Boys hostel, girls hostel, and high school',
  'પર્વ ઉજવણી': 'Festival Celebrations',
  'જન્માષ્ટમી, દિપાવલી, હોળી-ધૂળેટી, ગુરૂ પૂર્ણિમા': 'Janmashtami, Diwali, Holi-Dhuleti, and Guru Purnima',
  'હોળી મહોત્સવ સ્થાપના દિન': 'Holi Mahotsav and Foundation Day',
  'ગુરુપૂર્ણિમા મહોત્સવ': 'Guru Purnima Mahotsav',
  'જન્માષ્ટમી મહોત્સવ': 'Janmashtami Mahotsav',
  'દિપાવલી પર્વ': 'Diwali Festival',
  'આવનાર ઉત્સવ : દિપાવલી': 'Upcoming Festival: Diwali',
  'આવનાર ઉત્સવ : હોળી મહોત્સવ સ્થાપના દિવસ': 'Upcoming Festival: Holi Mahotsav Foundation Day',
  'અન્નક્ષેત્ર દાન': 'Annshetra Donation',
  'ગૌશાળા દાન': 'Gaushala Donation',
  'શૈક્ષણિક દાન': 'Education Donation',
  'મંદિર સેવા': 'Temple Seva',
  'ચકાસણી માટે સંપર્ક': 'Contact for Verification',
  '🪔 આગામી ઉત્સવ: દીપાવલી મહોત્સવ – ૨૦ ઓક્ટોબર ૨૦૨૬': 'Upcoming Festival: Diwali Mahotsav - 20 October 2026',
  'આવનાર ઉત્સવ ની યાદી': 'Upcoming Festival List',
  'ડોનેશન માટે અધિકૃત QR કોડ સ્કેન કરો. ચુકવણી કરતાં પહેલાં મંદિર સંપર્ક દ્વારા વિગતો ચકાસી લેવી.': 'Scan the official QR code for donation. Please verify details with the temple contact before payment.',
  'વડવાળા ધામનો ઇતિહાસ': 'History of Vadwala Dham',
  'મંદિરની ભવ્યતા': 'Grandeur of the Temple',
  'ત્રણ દ્વારો': 'Three Entrance Gates',
  'પાંચ દેવો': 'Five Deities',
  'અખિલ ભારતીય રબારી સમાજ ધર્મગુરુગાદી': 'Religious Seat of the All India Rabari Community',
  'વડવાળા ધામ સંક્ષિપ્ત પરિચય': 'Brief Introduction to Vadwala Dham',
  'આશ્રમ અને પવિત્ર પરિસર': 'Ashram and Sacred Campus',
  'મંદિર અને શિલ્પકલા': 'Temple and Architecture',
  'પવિત્ર વટવૃક્ષ અને સમાધિઓ': 'Sacred Banyan Tree and Samadhis',
  'અન્નપૂર્ણા ભંડાર અને ગૌસેવા': 'Annapurna Storehouse and Cow Service',
  'યાત્રિક નિવાસ અને સંત સેવા': 'Pilgrim Guesthouse and Saint Service',
  'ત્રણ પ્રવેશદ્વારો અને દેવો': 'Three Entrance Gates and Deities',
  'ગૌશાળા : વટેશ્વર ગૌશાળા અને ગૌ સેવા': 'Gaushala: Vateshwar Gaushala and Cow Service',
  'શૈક્ષણિક સેવાઓ : કુમાર અને કન્યા છાત્રાલયો': 'Educational Services: Boys and Girls Hostels',
  'પર્વ ઉજવણી : ભવ્ય ઉત્સવોનું આયોજન': 'Festival Celebrations: Organizing Grand Festivals',
  'ધાર્મિક સેવાઓ અને ધર્મશાળાઓ': 'Religious Services and Pilgrim Guesthouses',
  'મહાકુંભ અને આપાતકાલીન સેવા': 'Mahakumbh and Emergency Services',
  'આશ્રમ અને મંદિર પરિસર': 'Ashram and Temple Campus',
  'વટવૃક્ષ અને સમાધિ સ્થાન': 'Sacred Banyan Tree and Samadhi Sthal',
  'ભંડાર, અન્નક્ષેત્ર અને ગૌશાળા': 'Bhandar, Annshetra and Gaushala',
  'ત્રણ પ્રવેશ દ્વાર': 'Three Entrance Gates',
  'પાંચ દેવોના દર્શન': 'Darshan of Five Deities',
  // ── Gurus Translations ──
  'પરમ પૂજ્ય ૧૦૦૮ મહામંડલેશ્વર શ્રી કનીરામદાસજી બાપુ': 'Param Pujya 1008 Mahamandaleshwar Shri Kaniramdasji Bapu',
  'મહંત અને મહામંડલેશ્વર, શ્રી વડવાળા મંદિર, દુધરેજધામ': 'Mahant and Mahamandaleshwar, Shree Vadwala Mandir, Dudhrej Dham',
  'મહંત શ્રી કનીરામ બાપુ': 'Mahant Shri Kaniram Bapu',
  'રબારી / માલધારી સમાજના ધર્મગુરુ': 'Spiritual Leader of Rabari / Maldhari Community',
  'શ્રી વડવાળા મંદિર, દુધરેજધામ': 'Shree Vadwala Mandir, Dudhrej Dham',
  'પરમ પૂજ્ય મહામંડલેશ્વર શ્રી કનીરામદાસજી બાપુ, શ્રી વડવાળા મંદિર દુધરેજધામના ૨૨મા ગાદીપતિ, રબારી-માલધારી સમાજના આદરણીય ધર્મગુરુ છે. ધર્મ, સેવા, ગૌરક્ષા અને શિક્ષણ જેવા ક્ષેત્રોમાં તેમનું યોગદાન અમૂલ્ય છે.': 'Param Pujya Mahamandaleshwar Shri Kaniramdasji Bapu, the 22nd spiritual head of Shree Vadwala Mandir Dudhrej Dham, is the revered spiritual leader of the Rabari-Maldhari community. His contributions to religion, social service, cow protection, and education are invaluable.',
  'કોઠારી શ્રી મુકુંદરામ બાપુ': 'Kothari Shri Mukundram Bapu',
  'કોઠારી, શ્રી વડવાળા મંદિર, દુધરેજધામ': 'Kothari, Shree Vadwala Mandir, Dudhrej Dham',
  'કોઠારી અને મંદિરના વહીવટી વડા': 'Kothari and Administrative Head of Temple',
  'કોઠારી શ્રી મુકુંદરામ બાપુ, શ્રી વડવાળા મંદિર દુધરેજધામના કોઠારી અને વહીવટી વડા છે. ધામના ભંડાર, અન્નક્ષેત્ર, ગૌશાળા અને દૈનિક વ્યવસ્થાપનનું સંચાલન તેમના હસ્તક છે.': 'Kothari Shri Mukundram Bapu is the Kothari and administrative head of Shree Vadwala Mandir Dudhrej Dham. The management of the temple’s treasury, food hall, cowshed, and daily administration is handled by him.',
  'ગૌ માતાની સેવા કરવી એ સાક્ષાત નારાયણની સેવા છે.': 'Serving Mother Cow is serving the Lord directly.',
  'ધર્મ, શિક્ષણ અને સેવા – આ ત્રણ જ સમાજ ઉત્થાનના આધારસ્તંભ છે.': 'Religion, education, and service - these three are the pillars of societal upliftment.',
  'ગાદીપતિ પદ ગ્રહણ': 'Ascension to the Spiritual Seat (Gadipati)',
  'શ્રી વડવાળા મંદિર દુધરેજધામના ૨૨મા ગાદીપતિ તરીકે પદ ગ્રહણ કર્યું.': 'Ascended to the spiritual seat as the 22nd head of Shree Vadwala Mandir Dudhrej Dham.',
  'ગુરુ પૂર્ણિમા મહોત્સવ': 'Guru Purnima Mahotsav',
  'દર વર્ષે ગુરુ પૂર્ણિમાના પાવન પ્રસંગે ૨-૩ લાખ ભક્તો ધામમાં દર્શનાર્થે આવે છે. સંતવાણી, ગુરુ વંદના અને ભંડારાનું ભવ્ય આયોજન.': 'Every year on the sacred occasion of Guru Purnima, 2-3 lakh devotees visit the temple. Grand organization of devotional singing, guru worship, and community feasts.',
  'જન્માષ્ટમી, દિપાવલી અને હોળી મહોત્સવ': 'Janmashtami, Diwali, and Holi Celebrations',
  'ધામમાં ભક્તિભાવ અને ભવ્યતાથી ઉજવાતા મુખ્ય ધાર્મિક પર્વો, જ્યાં લાખો શ્રદ્ધાળુઓ ભાગ લે છે.': 'Major religious festivals celebrated with deep devotion and grandeur, drawing lakhs of devotees.',
  'ગૌશાળા સ્થાપના અને વિસ્તરણ': 'Establishment and Expansion of Cowshed',
  'શ્રી વડવાળા મંદિર ગૌશાળા, શ્રી વટેશ્વર ગૌશાળા (જેગડવા) અને શ્રી શીતલ ગૌશાળાની સ્થાપના – ૭૫૦+ ગીર ગાયોનો ઉછેર.': 'Establishment of Shree Vadwala Mandir Cowshed, Shree Vateshwar Cowshed (Jegadva), and Shree Shital Cowshed - rearing 750+ Gir cows.',
  'શ્રી શીતલ ગૌશાળા લોકાર્પણ': 'Inauguration of Shree Shital Gaushala',
  'હોળી મહોત્સવ ૨૦૨૬ના પાવન પ્રસંગે પૂજ્ય મોરારી બાપુ, જગદ્ગુરુ શંકરાચાર્ય, ૨૫૦+ મહામંડલેશ્વરો અને લાખો ભક્તોની ઉપસ્થિતિમાં ભવ્ય ઉદ્ઘાટન.': 'Grand inauguration on the holy occasion of Holi Mahotsav 2026, in the presence of revered Morari Bapu, Jagadguru Shankaracharya, 250+ Mahamandaleshwars, and lakhs of devotees.',
  'શૈક્ષણિક અને સામાજિક સેવા': 'Educational and Social Services',
  'કુમાર છાત્રાલય, કન્યા છાત્રાલય, વિદ્યાલય અને ધર્મશાળાઓનું સંચાલન.': 'Management of boys\' hostel, girls\' hostel, school, and pilgrim guesthouses.',
  'મહાકુંભ સેવા': 'Mahakumbh Service',
  'ઉજ્જૈન, નાસિક, પ્રયાગરાજ અને હરિદ્વારમાં મહાકુંભ પર્વે ભવ્ય અન્નક્ષેત્ર, વસ્ત્રદાન અને સાધુ-સંતોની સેવા.': 'Grand food services, clothing distribution, and service to saints during Mahakumbh in Ujjain, Nashik, Prayagraj, and Haridwar.',
  'ભંડાર અને અન્નક્ષેત્ર સંચાલન': 'Management of Storehouse and Food Hall',
  'દરરોજ ૧,૦૦૦ થી ૧,૫૦૦ દર્શનાર્થીઓ અને સાધુ-સંતો માટે ૨૪ કલાક અન્નક્ષેત્ર સેવાનું સંચાલન.': 'Managing 24-hour food hall service for 1,000 to 1,500 devotees and saints daily.',
  'પર્વ આયોજન': 'Festival Organization',
  'ગુરુ પૂર્ણિમા, જન્માષ્ટમી, દિપાવલી અને હોળી મહોત્સવમાં ૨-૩ લાખ ભક્તો માટે ભોજન, રહેવા અને પ્રસાદની વ્યવસ્થા.': 'Arranging food, accommodation, and holy offerings for 2-3 lakh devotees during major festivals.',
  'યાત્રિક સેવા': 'Pilgrim Hospitality Service',
  'ધામમાં આવતા યાત્રાળુઓ, સંતો અને દર્શનાર્થીઓ માટે નિવાસ, ભોજન અને અન્ય સગવડોનું સંચાલન.': 'Managing accommodation, dining, and other amenities for visiting pilgrims, saints, and devotees.',
  'ચાલુ': 'Ongoing',
  'દર વર્ષે': 'Annually',
  'માર્ચ ૨૦૨૬': 'March 2026',
  'દર્શન અને સેવા છબીઓ': 'Darshan and Service Gallery',
  'કોઠારી શ્રી મુકુંદરામ બાપુ – Kothari Shri Mukundram Bapu': 'Kothari Shri Mukundram Bapu',
  'ભંડાર સેવા – વડવાળા ધામ': 'Treasury Service - Vadvala Dham',
  'અન્નક્ષેત્ર સેવા – દુધરેજ ધામ': 'Food Hall Service - Dudhrej Dham',
  'ઉત્સવ આયોજન – ગુરુ પૂર્ણિમા': 'Festival Organization - Guru Purnima',
  'દૈનિક મંદિર સેવા': 'Daily Temple Worship',
  'મહામંડલેશ્વર શ્રી કનીરામદાસજી બાપુ': 'Mahamandaleshwar Shri Kaniramdasji Bapu',
  'ગુરુ પૂર્ણિમા મહોત્સવ – વડવાળા ધામ': 'Guru Purnima Mahotsav - Vadvala Dham',
  'શ્રી શીતલ ગૌશાળા લોકાર્પણ – માર્ચ ૨૦૨૬': 'Shree Shital Gaushala Inauguration - March 2026',
  'સંતવાણી કાર્યક્રમ': 'Santvani (Devotional Singing) Event',
  'ગૌશાળા દર્શન – ગીર ગાયો સાથે': 'Gir Cows of Gaushala',
  'હોળી મહોત્સવ – સ્થાપના દિવસ': 'Holi Mahotsav - Foundation Day',
  'જન્માષ્ટમી ઉત્સવ – વડવાળા મંદિર': 'Janmashtami Festival - Vadvala Temple',
  'દિપાવલી પર્વ – દુધરેજ ધામ': 'Diwali Festival - Dudhrej Dham',
  'વિદ્યાર્થીઓ સાથે – શૈક્ષણિક કાર્ય': 'With Students - Educational Service',
};

const generatedPrefixes = [
  ['દીપાવલી મહોત્સવ', 'Diwali Mahotsav'],
  ['જન્માષ્ટમી મહોત્સવ', 'Janmashtami Mahotsav'],
  ['ગુરુ પૂર્ણિમા', 'Guru Purnima'],
  ['હોળી મહોત્સવ', 'Holi Mahotsav'],
];

function translateToEnglish(text) {
  if (!text || typeof text !== 'string') return text;
  if (exactEnglish[text]) return exactEnglish[text];
  for (const [gu, en] of generatedPrefixes) {
    if (text.startsWith(gu)) return text.replace(gu, en);
  }
  return text;
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('site_language') || 'gu');

  useEffect(() => {
    localStorage.setItem('site_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    isGujarati: language === 'gu',
    setLanguage,
    toggleLanguage: () => setLanguage(prev => (prev === 'gu' ? 'en' : 'gu')),
    t: (key) => ui[language][key] || key,
    tr: (text) => (language === 'en' ? translateToEnglish(text) : text),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
