import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const ui = {
  gu: {
    home: 'હોમ',
    history: 'ઇતિહાસ',
    seva: 'સેવા',
    gallery: 'ગેલેરી',
    videos: 'વિડીયો',
    donate: 'દાન',
    contact: 'સંપર્ક',
    changeLanguage: 'English',
    donateNow: 'દાન કરો',
    viewGallery: 'ગેલેરી જુઓ',
    exploreSeva: 'સેવા જુઓ',
    dailyMeals: 'દૈનિક પ્રસાદ',
    festivalDevotees: 'ઉત્સવના ભક્તો',
    annshetra: 'અન્નક્ષેત્ર',
    founded: 'શ્રદ્ધા અને સેવાનું પવિત્ર ધામ',
    aboutTemple: 'મંદિર વિશે',
    dailyWorship: 'દૈનિક આરતી',
    dailyWorshipText: 'સવાર અને સાંજની આરતી',
    sacredTradition: 'પવિત્ર પરંપરા',
    sacredTraditionText: 'સદીઓનો આધ્યાત્મિક વારસો',
    ourSeva: 'અમારી સેવા',
    serviceDevotion: 'સેવા એ ભક્તિ',
    serviceSubtitle: 'મંદિરની સેવા પ્રવૃત્તિઓ સમાજસેવાના મુખ્ય સ્તંભો છે.',
    learnMore: 'વધુ જાણો',
    sacredCalendar: 'પવિત્ર પર્વો',
    festivalsCelebrations: 'ઉત્સવો અને ઉજવણી',
    festivalsSubtitle: 'મંદિરમાં ભક્તિભાવ અને ભવ્યતાથી ઉજવાતા મુખ્ય પર્વો.',
    upcoming: 'આવનાર',
    viewAllFestivals: 'બધા ઉત્સવો જુઓ',
    visualStories: 'પવિત્ર ક્ષણો',
    photoGallery: 'ફોટો ગેલેરી',
    gallerySubtitle: 'મંદિરના ઉત્સવો, દર્શન અને સેવાકાર્યોના ફોટા.',
    fullGallery: 'પૂર્ણ ગેલેરી જુઓ',
    supportMission: 'સેવામાં સહયોગ',
    contributeNow: 'દાન કરો',
    getInTouch: 'સંપર્કમાં રહો',
    visitConnect: 'મુલાકાત અથવા સંપર્ક',
    contactSubtitle: 'દર્શન, નિવાસ અથવા માર્ગદર્શન માટે ભક્તો અને મુલાકાતીઓ સંપર્ક કરી શકે છે.',
    address: 'સરનામું',
    phone: 'ફોન',
    email: 'ઈમેઈલ',
    website: 'વેબસાઈટ',
    comingSoon: 'ટૂંક સમયમાં',
    quickLinks: 'ઝડપી લિંક્સ',
    footerSeva: 'અમારી સેવા',
    footerDesc: 'ગુજરાતમાં ભક્તિ, સમાજસેવા અને પવિત્ર પરંપરાનું જીવંત કેન્દ્ર.',
    footerTagline: 'સેવા · ભક્તિ · જ્ઞાન',
    built: 'ભક્તિથી બનાવેલ.',
    historySubtitle: 'વડવાળા ધામનો ગૌરવશાળી ઇતિહાસ',
    noHistory: 'ઇતિહાસની માહિતી ટૂંક સમયમાં ઉપલબ્ધ થશે',
    parampara: 'આચાર્યશ્રી પરંપરા',
    paramparaSubtitle: 'ગાદીસ્થ આચાર્યશ્રીઓની પરંપરા',
    all: 'બધા',
    noPhotos: 'આ કેટેગરીમાં હાલમાં કોઈ ફોટો નથી',
    donationTitle: 'દાન – સેવા',
    donationSubtitle: 'મંદિરના વિવિધ સેવા કાર્યોમાં આપનો સહકાર',
    donationPurposes: 'દાનના હેતુઓ',
    donationPurposesSub: 'નીચેના સેવા કાર્યોમાં દાન આપી શકો છો',
    howToDonate: 'દાન કેવી રીતે કરવું',
    noDonation: 'દાનની માહિતી ટૂંક સમયમાં ઉપલબ્ધ થશે',
    noPayment: 'ચુકવણીની માહિતી ટૂંક સમયમાં ઉપલબ્ધ થશે',
    importantNote: 'મહત્વની નોંધ',
    activitiesTitle: 'સેવા અને ઉત્સવો',
    activitiesSubtitle: 'મંદિરની સેવા, શૈક્ષણિક અને ધાર્મિક પ્રવૃત્તિઓ',
    ourMission: 'અમારો ધ્યેય',
    serviceActivities: 'સેવા પ્રવૃત્તિઓ',
    activitiesSoon: 'પ્રવૃત્તિઓ ટૂંક સમયમાં ઉપલબ્ધ થશે',
    festivals: 'ઉત્સવો',
    festivalInfoSoon: 'ઉત્સવની માહિતી ટૂંક સમયમાં ઉપલબ્ધ થશે',
    videosTitle: 'વિડીયો અને રીલ્સ',
    videosSubtitle: 'મંદિરના ઉત્સવો અને દર્શનના વિડીયો',
    latestVideos: 'નવા વિડીયો',
    latestReels: 'નવી રીલ્સ',
    noVideos: 'હાલમાં કોઈ વિડીયો ઉપલબ્ધ નથી',
    noReels: 'હાલમાં કોઈ રીલ્સ ઉપલબ્ધ નથી',
    contactUs: 'અમારો સંપર્ક કરો',
    reachOut: 'સંપર્ક કરો',
    contactInfo: 'સંપર્ક માહિતી',
    sendMessage: 'સંદેશ મોકલો',
    writeToUs: 'અમને લખો',
    name: 'તમારું નામ *',
    phoneNumber: 'ફોન નંબર',
    message: 'તમારો સંદેશ *',
    namePlaceholder: 'તમારું નામ લખો',
    phonePlaceholder: 'ફોન નંબર લખો',
    emailPlaceholder: 'ઈમેઈલ લખો',
    messagePlaceholder: 'તમારો સંદેશ લખો...',
    sending: 'મોકલી રહ્યા છીએ...',
    sent: 'તમારો સંદેશ સફળતાપૂર્વક મોકલાયો!',
    send: 'સંદેશ મોકલો',
    findUs: 'અમને શોધો',
    dhaja: 'ધજા',
    gaushala: 'ગૌશાળા',
    location: 'અમારું સ્થાન',
    // ── Gurus ──
    guruEyebrow: 'ધર્મગુરુ પરંપરા',
    guruParampara: 'ગુરુ પરંપરા',
    readMore: 'વધુ વાંચો',
    loadingGurus: 'લોડ થઈ રહ્યું છે...',
    guruNotFound: 'ગુરુ વિશે માહિતી ઉપલબ્ધ નથી',
    backToHome: 'હોમ પેજ પર પાછા ફરો',
    back: 'પાછા',
    born: 'જન્મ',
    birthplace: 'જન્મસ્થળ',
    lifeHistory: 'જીવન ચરિત્ર',
    biographyTitle: 'પૂર્ણ જીવન ગાથા',
    teachings: 'ઉપદેશ અને સંદેશ',
    teachingsTitle: 'મુખ્ય સિદ્ધાંતો અને સંદેશો',
    timeline: 'સમયરેખા',
    timelineTitle: 'મહત્વના સેવા કાર્યો અને ઘટનાક્રમ',
    galleryTitle: 'દર્શન અને સેવા છબીઓ',
    upcomingTithis: 'આવનાર તિથિઓ',
    tithisSubtitle: 'ક્યારેય મૂંઝવણમાં ન પડો - આગામી પૂનમ, બીજ અને અન્ય મહત્વપૂર્ણ દિવસોની માહિતી અહીં જુઓ.',
    nextPunamIs: 'આગામી પૂનમ:',
    nextBijIs: 'આગામી બીજ:',
    filterAll: 'બધી તિથિઓ',
    filterPunam: 'ફક્ત પૂનમ',
    filterBij: 'ફક્ત બીજ',
    nextBadge: 'આગામી',
  },
  en: {
    home: 'Home',
    history: 'History',
    seva: 'Seva',
    gallery: 'Gallery',
    videos: 'Videos',
    donate: 'Donate',
    contact: 'Contact',
    changeLanguage: 'ગુજરાતી',
    donateNow: 'Donate',
    viewGallery: 'View Gallery',
    exploreSeva: 'Explore Seva',
    dailyMeals: 'Daily Meals',
    festivalDevotees: 'Festival Devotees',
    annshetra: 'Annshetra',
    founded: 'Founded on Faith · Serving Humanity',
    aboutTemple: 'About the Temple',
    dailyWorship: 'Daily Worship',
    dailyWorshipText: 'Morning and evening aarti',
    sacredTradition: 'Sacred Tradition',
    sacredTraditionText: 'Centuries of spiritual heritage',
    ourSeva: 'Our Seva',
    serviceDevotion: 'Service as Devotion',
    serviceSubtitle: "The temple's mission flows through community service, education, worship, and care.",
    learnMore: 'Learn more',
    sacredCalendar: 'Sacred Calendar',
    festivalsCelebrations: 'Festivals & Celebrations',
    festivalsSubtitle: 'Major religious festivals celebrated at the temple with devotion and grandeur.',
    upcoming: 'Upcoming',
    viewAllFestivals: 'View All Festivals',
    visualStories: 'Visual Stories',
    photoGallery: 'Photo Gallery',
    gallerySubtitle: 'Glimpses of temple festivals, darshan, and service activities.',
    fullGallery: 'View Full Gallery',
    supportMission: 'Support the Mission',
    contributeNow: 'Contribute Now',
    getInTouch: 'Get in Touch',
    visitConnect: 'Visit or Connect',
    contactSubtitle: 'Devotees and visitors can reach out for darshan, accommodation, or guidance.',
    address: 'Address',
    phone: 'Phone',
    email: 'Email',
    website: 'Website',
    comingSoon: 'Coming soon',
    quickLinks: 'Quick Links',
    footerSeva: 'Our Seva',
    footerDesc: 'A living center of devotion, community service, and sacred tradition in Gujarat.',
    footerTagline: 'Seva · Bhakti · Gyaan',
    attribution: 'Content reference',
    originalUi: 'All UI design is original and not affiliated with the source website.',
    built: 'Built with devotion.',
    historySubtitle: 'The proud history of Vadwala Dham',
    noHistory: 'History information will be available soon',
    parampara: 'Acharya Parampara',
    paramparaSubtitle: 'Lineage of the presiding Acharyas',
    all: 'All',
    noPhotos: 'No photos are available in this category',
    donationTitle: 'Donation & Seva',
    donationSubtitle: 'Support the temple service activities',
    donationPurposes: 'Donation Purposes',
    donationPurposesSub: 'You can donate toward the service activities below',
    howToDonate: 'How to Donate',
    noDonation: 'Donation information will be available soon',
    noPayment: 'Payment information will be available soon',
    importantNote: 'Important Note',
    activitiesTitle: 'Seva & Festivals',
    activitiesSubtitle: 'Temple service, education, and religious activities',
    ourMission: 'Our Mission',
    serviceActivities: 'Service Activities',
    activitiesSoon: 'Activities coming soon',
    festivals: 'Festivals',
    dhaja: 'Dhaja',
    gaushala: 'Gaushala',
    festivalInfoSoon: 'Festival information coming soon',
    videosTitle: 'Videos and Reels',
    videosSubtitle: 'Temple festival and darshan videos',
    latestVideos: 'Latest Videos',
    latestReels: 'Latest Reels',
    noVideos: 'No videos are available right now',
    noReels: 'No reels are available right now',
    contactUs: 'Contact Us',
    reachOut: 'Reach Out',
    contactInfo: 'Contact Information',
    sendMessage: 'Send a Message',
    writeToUs: 'Write to Us',
    name: 'Your Name *',
    phoneNumber: 'Phone Number',
    message: 'Your Message *',
    namePlaceholder: 'Enter your name',
    phonePlaceholder: 'Enter phone number',
    emailPlaceholder: 'Enter email',
    messagePlaceholder: 'Write your message...',
    sending: 'Sending...',
    sent: 'Your message was sent successfully!',
    send: 'Send Message',
    findUs: 'Find Us',
    location: 'Our Location',
    // ── Gurus ──
    guruEyebrow: 'Holy Gurus',
    guruParampara: 'Guru Parampara',
    readMore: 'Read More',
    loadingGurus: 'Loading guru details...',
    guruNotFound: 'Guru details not found',
    backToHome: 'Back to Home',
    back: 'Back',
    born: 'Born',
    birthplace: 'Birthplace',
    lifeHistory: 'Biography',
    biographyTitle: 'Life History & Contributions',
    teachings: 'Teachings & Message',
    teachingsTitle: 'Key Themes and Teachings',
    timeline: 'Timeline',
    timelineTitle: 'Key Milestones and Service Timeline',
    galleryTitle: 'Darshan & Service Gallery',
    upcomingTithis: 'Upcoming Tithis',
    tithisSubtitle: 'Never get confused again – see the next Punam, Bij and other important days here.',
    nextPunamIs: 'Next Punam:',
    nextBijIs: 'Next Bij:',
    filterAll: 'All Tithis',
    filterPunam: 'Punam Only',
    filterBij: 'Bij Only',
    nextBadge: 'Next',
  },
};

const exactEnglish = {
  'શ્રી વડવાળા મંદિર દુધરેજધામ': 'Shree Vadwala Mandir Dudhrejdham',
  'શ્રી વડવાળાદેવના પવિત્ર ધામમાં આપનું સ્વાગત છે': 'Welcome to the sacred abode of Shri Vadwaladev.',
  'અન્નક્ષેત્ર : અભિયાગત સેવા': 'Annshetra: Devotee Meal Service',
  'દરરોજ ૨૪ કલાક અન્નક્ષેત્ર': '24-hour daily meal service',
  'ગૌશાળા : ઉત્તમ ઓલાદનું રક્ષણ': 'Gaushala: Care for Indigenous Cattle',
  'ઉત્તમ ગાયોનો ઉછેર અને સેવા': 'Care and service for indigenous cattle',
  'શૈક્ષણિક કાર્ય': 'Educational Service',
  'કુમાર છાત્રાલય, કન્યા છાત્રાલય, હાઈસ્કુલ': 'Boys hostel, girls hostel, and high school',
  'પર્વ ઉજવણી': 'Festival Celebrations',
  'જન્માષ્ટમી, દિપાવલી, હોળી-ધૂળેટી, ગુરૂ પૂર્ણિમા': 'Janmashtami, Diwali, Holi-Dhuleti, and Guru Purnima',
  'હોળી મહોત્સવ સ્થાપના દિન': 'Holi Mahotsav and Foundation Day',
  'ગુરુપૂર્ણિમા મહોત્સવ': 'Guru Purnima Mahotsav',
  'જન્માષ્ટમી મહોત્સવ': 'Janmashtami Mahotsav',
  'દિપાવલી પર્વ': 'Diwali Festival',
  'આવનાર ઉત્સવ : દિપાવલી': 'Upcoming Festival: Diwali',
  'આવનાર ઉત્સવ : હોળી મહોત્સવ સ્થાપના દિવસ': 'Upcoming Festival: Holi Mahotsav Foundation Day',
  'અન્નક્ષેત્ર દાન': 'Annshetra Donation',
  'ગૌશાળા દાન': 'Gaushala Donation',
  'શૈક્ષણિક દાન': 'Education Donation',
  'મંદિર સેવા': 'Temple Seva',
  'ચકાસણી માટે સંપર્ક': 'Contact for Verification',
  '🪔 આગામી ઉત્સવ: દીપાવલી મહોત્સવ – ૨૦ ઓક્ટોબર ૨૦૨૬': 'Upcoming Festival: Diwali Mahotsav - 20 October 2026',
  'આવનાર ઉત્સવ ની યાદી': 'Upcoming Festival List',
  'ડોનેશન માટે અધિકૃત QR કોડ સ્કેન કરો. ચુકવણી કરતાં પહેલાં મંદિર સંપર્ક દ્વારા વિગતો ચકાસી લેવી.': 'Scan the official QR code for donation. Please verify details with the temple contact before payment.',
  'વડવાળા ધામનો ઇતિહાસ': 'History of Vadwala Dham',
  'મંદિરની ભવ્યતા': 'Grandeur of the Temple',
  'ત્રણ દ્વારો': 'Three Entrance Gates',
  'પાંચ દેવો': 'Five Deities',
  'અખિલ ભારતીય રબારી સમાજ ધર્મગુરુગાદી': 'Religious Seat of the All India Rabari Community',
  'વડવાળા ધામ સંક્ષિપ્ત પરિચય': 'Brief Introduction to Vadwala Dham',
  'આશ્રમ અને મંદિર પરિસર': 'Ashram and Temple Campus',
  'વટવૃક્ષ અને સમાધિ સ્થાન': 'Sacred Banyan Tree and Samadhi Sthal',
  'ભંડાર, અન્નક્ષેત્ર અને ગૌશાળા': 'Bhandar, Annshetra and Gaushala',
  'યાત્રિક નિવાસ અને સંત સેવા': 'Pilgrim Stay and Saint Service',
  'ત્રણ પ્રવેશ દ્વાર': 'Three Entrance Gates',
  'પાંચ દેવોના દર્શન': 'Darshan of Five Deities',
  // ── Gurus Translations ──
  'પરમ પૂજ્ય ૧૦૦૮ મહામંડલેશ્વર શ્રી કનીરામદાસજી બાપુ': 'Param Pujya 1008 Mahamandaleshwar Shri Kaniramdasji Bapu',
  'મહંત અને મહામંડલેશ્વર, શ્રી વડવાળા મંદિર, દુધરેજધામ': 'Mahant and Mahamandaleshwar, Shree Vadwala Mandir, Dudhrej Dham',
  'મહંત શ્રી કનીરામ બાપુ': 'Mahant Shri Kaniram Bapu',
  'રબારી / માલધારી સમાજના ધર્મગુરુ': 'Spiritual Leader of Rabari / Maldhari Community',
  'શ્રી વડવાળા મંદિર, દુધરેજધામ': 'Shree Vadwala Mandir, Dudhrej Dham',
  'પરમ પૂજ્ય મહામંડલેશ્વર શ્રી કનીરામદાસજી બાપુ, શ્રી વડવાળા મંદિર દુધરેજધામના ૨૨મા ગાદીપતિ, રબારી-માલધારી સમાજના આદરણીય ધર્મગુરુ છે. ધર્મ, સેવા, ગૌરક્ષા અને શિક્ષણ જેવા ક્ષેત્રોમાં તેમનું યોગદાન અમૂલ્ય છે.': 'Param Pujya Mahamandaleshwar Shri Kaniramdasji Bapu, the 22nd spiritual head of Shree Vadwala Mandir Dudhrej Dham, is the revered spiritual leader of the Rabari-Maldhari community. His contributions to religion, social service, cow protection, and education are invaluable.',
  'કોઠારી શ્રી મુકુંદરામ બાપુ': 'Kothari Shri Mukundram Bapu',
  'કોઠારી, શ્રી વડવાળા મંદિર, દુધરેજધામ': 'Kothari, Shree Vadwala Mandir, Dudhrej Dham',
  'કોઠારી અને મંદિરના વહીવટી વડા': 'Kothari and Administrative Head of Temple',
  'કોઠારી શ્રી મુકુંદરામ બાપુ, શ્રી વડવાળા મંદિર દુધરેજધામના કોઠારી અને વહીવટી વડા છે. ધામના ભંડાર, અન્નક્ષેત્ર, ગૌશાળા અને દૈનિક વ્યવસ્થાપનનું સંચાલન તેમના હસ્તક છે.': 'Kothari Shri Mukundram Bapu is the Kothari and administrative head of Shree Vadwala Mandir Dudhrej Dham. The management of the temple’s treasury, food hall, cowshed, and daily administration is handled by him.',
  'ગૌ માતાની સેવા કરવી એ સાક્ષાત નારાયણની સેવા છે.': 'Serving Mother Cow is serving the Lord directly.',
  'ધર્મ, શિક્ષણ અને સેવા – આ ત્રણ જ સમાજ ઉત્થાનના આધારસ્તંભ છે.': 'Religion, education, and service - these three are the pillars of societal upliftment.',
  'ગાદીપતિ પદ ગ્રહણ': 'Ascension to the Spiritual Seat (Gadipati)',
  'શ્રી વડવાળા મંદિર દુધરેજધામના ૨૨મા ગાદીપતિ તરીકે પદ ગ્રહણ કર્યું.': 'Ascended to the spiritual seat as the 22nd head of Shree Vadwala Mandir Dudhrej Dham.',
  'ગુરુ પૂર્ણિમા મહોત્સવ': 'Guru Purnima Mahotsav',
  'દર વર્ષે ગુરુ પૂર્ણિમાના પાવન પ્રસંગે ૨-૩ લાખ ભક્તો ધામમાં દર્શનાર્થે આવે છે. સંતવાણી, ગુરુ વંદના અને ભંડારાનું ભવ્ય આયોજન.': 'Every year on the sacred occasion of Guru Purnima, 2-3 lakh devotees visit the temple. Grand organization of devotional singing, guru worship, and community feasts.',
  'જન્માષ્ટમી, દિપાવલી અને હોળી મહોત્સવ': 'Janmashtami, Diwali, and Holi Celebrations',
  'ધામમાં ભક્તિભાવ અને ભવ્યતાથી ઉજવાતા મુખ્ય ધાર્મિક પર્વો, જ્યાં લાખો શ્રદ્ધાળુઓ ભાગ લે છે.': 'Major religious festivals celebrated with deep devotion and grandeur, drawing lakhs of devotees.',
  'ગૌશાળા સ્થાપના અને વિસ્તરણ': 'Establishment and Expansion of Cowshed',
  'શ્રી વડવાળા મંદિર ગૌશાળા, શ્રી વટેશ્વર ગૌશાળા (જેગડવા) અને શ્રી શીતલ ગૌશાળાની સ્થાપના – ૭૫૦+ ગીર ગાયોનો ઉછેર.': 'Establishment of Shree Vadwala Mandir Cowshed, Shree Vateshwar Cowshed (Jegadva), and Shree Shital Cowshed - rearing 750+ Gir cows.',
  'શ્રી શીતલ ગૌશાળા લોકાર્પણ': 'Inauguration of Shree Shital Gaushala',
  'હોળી મહોત્સવ ૨૦૨૬ના પાવન પ્રસંગે પૂજ્ય મોરારી બાપુ, જગદ્ગુરુ શંકરાચાર્ય, ૨૫૦+ મહામંડલેશ્વરો અને લાખો ભક્તોની ઉપસ્થિતિમાં ભવ્ય ઉદ્ઘાટન.': 'Grand inauguration on the holy occasion of Holi Mahotsav 2026, in the presence of revered Morari Bapu, Jagadguru Shankaracharya, 250+ Mahamandaleshwars, and lakhs of devotees.',
  'શૈક્ષણિક અને સામાજિક સેવા': 'Educational and Social Services',
  'કુમાર છાત્રાલય, કન્યા છાત્રાલય, વિદ્યાલય અને ધર્મશાળાઓનું સંચાલન.': 'Management of boys\' hostel, girls\' hostel, school, and pilgrim guesthouses.',
  'મહાકુંભ સેવા': 'Mahakumbh Service',
  'ઉજ્જૈન, નાસિક, પ્રયાગરાજ અને હરિદ્વારમાં મહાકુંભ પર્વે ભવ્ય અન્નક્ષેત્ર, વસ્ત્રદાન અને સાધુ-સંતોની સેવા.': 'Grand food services, clothing distribution, and service to saints during Mahakumbh in Ujjain, Nashik, Prayagraj, and Haridwar.',
  'ભંડાર અને અન્નક્ષેત્ર સંચાલન': 'Management of Storehouse and Food Hall',
  'દરરોજ ૧,૦૦૦ થી ૧,૫૦૦ દર્શનાર્થીઓ અને સાધુ-સંતો માટે ૨૪ કલાક અન્નક્ષેત્ર સેવાનું સંચાલન.': 'Managing 24-hour food hall service for 1,000 to 1,500 devotees and saints daily.',
  'પર્વ આયોજન': 'Festival Organization',
  'ગુરુ પૂર્ણિમા, જન્માષ્ટમી, દિપાવલી અને હોળી મહોત્સવમાં ૨-૩ લાખ ભક્તો માટે ભોજન, રહેવા અને પ્રસાદની વ્યવસ્થા.': 'Arranging food, accommodation, and holy offerings for 2-3 lakh devotees during major festivals.',
  'યાત્રિક સેવા': 'Pilgrim Hospitality Service',
  'ધામમાં આવતા યાત્રાળુઓ, સંતો અને દર્શનાર્થીઓ માટે નિવાસ, ભોજન અને અન્ય સગવડોનું સંચાલન.': 'Managing accommodation, dining, and other amenities for visiting pilgrims, saints, and devotees.',
  'ચાલુ': 'Ongoing',
  'દર વર્ષે': 'Annually',
  'માર્ચ ૨૦૨૬': 'March 2026',
  'દર્શન અને સેવા છબીઓ': 'Darshan and Service Gallery',
  'કોઠારી શ્રી મુકુંદરામ બાપુ – Kothari Shri Mukundram Bapu': 'Kothari Shri Mukundram Bapu',
  'ભંડાર સેવા – વડવાળા ધામ': 'Treasury Service - Vadvala Dham',
  'અન્નક્ષેત્ર સેવા – દુધરેજ ધામ': 'Food Hall Service - Dudhrej Dham',
  'ઉત્સવ આયોજન – ગુરુ પૂર્ણિમા': 'Festival Organization - Guru Purnima',
  'દૈનિક મંદિર સેવા': 'Daily Temple Worship',
  'મહામંડલેશ્વર શ્રી કનીરામદાસજી બાપુ': 'Mahamandaleshwar Shri Kaniramdasji Bapu',
  'ગુરુ પૂર્ણિમા મહોત્સવ – વડવાળા ધામ': 'Guru Purnima Mahotsav - Vadvala Dham',
  'શ્રી શીતલ ગૌશાળા લોકાર્પણ – માર્ચ ૨૦૨૬': 'Shree Shital Gaushala Inauguration - March 2026',
  'સંતવાણી કાર્યક્રમ': 'Santvani (Devotional Singing) Event',
  'ગૌશાળા દર્શન – ગીર ગાયો સાથે': 'Gir Cows of Gaushala',
  'હોળી મહોત્સવ – સ્થાપના દિવસ': 'Holi Mahotsav - Foundation Day',
  'જન્માષ્ટમી ઉત્સવ – વડવાળા મંદિર': 'Janmashtami Festival - Vadvala Temple',
  'દિપાવલી પર્વ – દુધરેજ ધામ': 'Diwali Festival - Dudhrej Dham',
  'વિદ્યાર્થીઓ સાથે – શૈક્ષણિક કાર્ય': 'With Students - Educational Service',
};

const generatedPrefixes = [
  ['દીપાવલી મહોત્સવ', 'Diwali Mahotsav'],
  ['જન્માષ્ટમી મહોત્સવ', 'Janmashtami Mahotsav'],
  ['ગુરુ પૂર્ણિમા', 'Guru Purnima'],
  ['હોળી મહોત્સવ', 'Holi Mahotsav'],
];

function translateToEnglish(text) {
  if (!text || typeof text !== 'string') return text;
  if (exactEnglish[text]) return exactEnglish[text];
  for (const [gu, en] of generatedPrefixes) {
    if (text.startsWith(gu)) return text.replace(gu, en);
  }
  return text;
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('site_language') || 'gu');

  useEffect(() => {
    localStorage.setItem('site_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    isGujarati: language === 'gu',
    setLanguage,
    toggleLanguage: () => setLanguage(prev => (prev === 'gu' ? 'en' : 'gu')),
    t: (key) => ui[language][key] || key,
    tr: (text) => (language === 'en' ? translateToEnglish(text) : text),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
